require("kris.plugins-setup")
require("kris.core.options")
require("kris.core.keymaps")
require("kris.core.colorscheme")
require("kris.plugins.nvim-cmp")
require("kris.lsp.lspconfig")
require("kris.plugins.comment")
require("kris.plugins.nvim-tree")
require("kris.plugins.lualine")
require("kris.plugins.telescope")
require("kris.plugins.autopairs")
require("kris.plugins.treesitter")
require("kris.plugins.gitsigns")

-- vim.opt.rtp:append("~/Engineering/neovim/plugins/present.nvim")
-- vim.opt.rtp:append("~/Engineering/neovim/plugins/todo.nvim")
